### ISSUE TITLE
Bad repository url in PyPI

### ISSUE THREAD

**Issue by xliiv** [figo-connect/schwifty#8]
Currently:
`http://github.com/figo-connect/schwfity`

actual:
`https://github.com/figo-connect/schwifty`

**Comment by berend** [comment]
that typo was fixed in https://github.com/figo-connect/schwifty/commit/e197373ff439032d859526a6e331fe32c2813c5e,[ the (latest) version on pypi](https://pypi.python.org/pypi/schwifty) also does not have this typo. Where did you find it?

**Comment by xliiv** [comment]
I've found it on the web?
It's here https://pypi.python.org/pypi/schwifty/1.0.1
It's definitely an old version.
My bad I check it.
Sorry, for the mess.
